# Generated by Django 4.0 on 2025-02-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_user_details_kcno'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='image_pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField()),
                ('pic_path', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='patient_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_no', models.CharField(max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('addr', models.CharField(max_length=1000)),
                ('pin', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='patient_doctor_query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('doctor_id', models.IntegerField()),
                ('msg', models.CharField(max_length=1000)),
                ('m_dt', models.CharField(max_length=20)),
                ('m_tm', models.CharField(max_length=20)),
                ('reply', models.CharField(max_length=1000)),
                ('r_dt', models.CharField(max_length=20)),
                ('r_tm', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='patient_login_map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('patient_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='test_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('pic_path', models.CharField(max_length=200)),
                ('dt', models.CharField(max_length=40)),
                ('tm', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
