# Generated by Django 4.0 on 2025-10-02 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_category_settings_doctor_details_image_pool_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctor_details',
        ),
        migrations.DeleteModel(
            name='patient_doctor_query',
        ),
    ]
