# Generated by Django 4.0 on 2025-10-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_doctor_details_delete_patient_doctor_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_pool',
            name='pic_path2',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
