# Generated by Django 4.0 on 2025-10-02 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_image_pool_pic_path2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patient_details',
        ),
        migrations.DeleteModel(
            name='patient_login_map',
        ),
        migrations.RenameField(
            model_name='image_pool',
            old_name='pic_path2',
            new_name='result',
        ),
        migrations.RenameField(
            model_name='test_history',
            old_name='patient_id',
            new_name='staff_id',
        ),
    ]
