# Generated by Django 4.0 on 2026-08-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_patient_details_delete_patient_login_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_history',
            name='d_type',
            field=models.CharField(default='image', max_length=10),
        ),
    ]
