# Generated by Django 4.0 on 2026-08-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_test_history_d_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_pool',
            name='d_type',
            field=models.CharField(default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='image_pool',
            name='dt',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='image_pool',
            name='tm',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
