"""
Django settings for Ai-WildEye project.

Generated by 'django-admin startproject' using Django 3.1.6.
Updated for modernization while preserving backward compatibility.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'p)_v^mgsyl&2x-fpsxfh=n)w=b-cc%7$3&9tvfm)q+ay5r@!ib'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if os.environ.get('DJANGO_ALLOWED_HOSTS') else []


# Application definition

INSTALLED_APPS = [
    'myapp',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'frontend/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

# Additional static file directories (frontend assets)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'frontend/static'),
]

# Media files (User uploads - kept in myapp/static/myapp/media for camera template compatibility)
MEDIA_ROOT = os.path.join(BASE_DIR, './myapp/static/myapp/media')
MEDIA_URL = '/media/'

# ===========================================
# Ai-WildEye Configuration
# ===========================================

# Camera Configuration
CAMERA_VIDEO_URL = os.environ.get(
    'WILDEYE_CAMERA_VIDEO_URL',
    'http://192.168.2.173:4747/video'
)
CAMERA_FRAME_URL = os.environ.get(
    'WILDEYE_CAMERA_FRAME_URL',
    'http://192.168.2.173:4747/cam/1/frame.jpg'
)

# Email Configuration
EMAIL_SMTP_HOST = os.environ.get('WILDEYE_EMAIL_SMTP_HOST', 'smtp.gmail.com')
EMAIL_SMTP_PORT = int(os.environ.get('WILDEYE_EMAIL_SMTP_PORT', '587'))
EMAIL_SENDER = os.environ.get('WILDEYE_EMAIL_SENDER', 'wildeye2026@gmail.com')
EMAIL_PASSWORD = os.environ.get('WILDEYE_EMAIL_PASSWORD', 'rgww pfxi huno frig')

# ML Configuration
ML_MODEL_PATH = os.environ.get('WILDEYE_ML_MODEL_PATH', 'backend/ml/mobilenet_animal_classifier_cpu.h5')
ML_LABELS_PATH = os.environ.get('WILDEYE_ML_LABELS_PATH', 'backend/ml/labels.txt')

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'myapp': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': True,
        },
    },
}